a=int(input("a oldal:"))
b=int(input("b oldal:"))
import turtle
ablak = turtle.Screen()
Sanyi = turtle.Turtle()
ablak = turtle.Screen()
ablak.bgcolor("black")
ablak.title("MAGYAR!!")
Sanyi.color("White")

Sanyi.forward(a)
Sanyi.left(90)
Sanyi.forward(b)
Sanyi.left(90)
Sanyi.forward(a)
Sanyi.left(90)
Sanyi.forward(a)
Sanyi.left(90)
Sanyi.right(90)
Sanyi.forward(a)
Sanyi.left(90)
Sanyi.forward(a)
Sanyi.left(90)
Sanyi.forward(a)
Sanyi.left(90)
Sanyi.forward(a)
Sanyi.left(90)
Sanyi.left(270)
Sanyi.forward(a)
Sanyi.left(90)
Sanyi.forward(a)
Sanyi.left(90)
Sanyi.forward(a)
Sanyi.left(90)
Sanyi.forward(a)
Sanyi.left(90)
Sanyi.forward(a)
Sanyi.right(90)
Sanyi.forward(a)
Sanyi.right(90)
Sanyi.forward(a)
Sanyi.left(90)
Sanyi.forward(a)
Sanyi.left(90)
Sanyi.forward(a)
Sanyi.left(90)


ablak.mainloop()