import turtle
ablak = turtle.Screen()
Sanyi = turtle.Turtle()
Sanyi.forward(400)
Sanyi.left(90)
Sanyi.forward(400)
Sanyi.left(90)
Sanyi.forward(400)
Sanyi.left(90)
Sanyi.forward(400)
ablak.mainloop()